name: cla

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cla:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'harpertoken'
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            signed.json

      - name: Checkout private cla-bot
        uses: actions/checkout@v4
        with:
          repository: bniladridas/cla-bot
          token: ${{ secrets.CLA_BOT_TOKEN }}
          path: cla-bot

      - name: Copy signed.json to cla-signers.json
        run: |
          cp signed.json cla-signers.json
          cp signed.json cla-bot/cla-signers.json

      - name: Run CLA bot
        uses: ./cla-bot/
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          signed.json: ${{ secrets.CLA_SIGNED_JSON }}
